### ISSUE TITLE
[Error] Buyer portal erroneously changes to seller portal while reloading

### ISSUE THREAD

**Issue by Kshitij1K** [localghosts/store-it#1]
Steps to replicate:
1) Login as a buyer in one tab
2) Open another tab, and login as a seller
3) Reloading the buyer tab brings up the seller portal

Basically, at a time only one type of user can be logged in. Logging in as another user removes the previous user's login.

**Comment by 1-Harshit** [comment]
At the same time, on the same portal using one web browser, you cannot log in to multiple accounts. Even when the two accounts are of separate types of users.

Thanks
Team localghosts
